PEP8:
  stage: test
  image:
    name: alpine/flake8
    entrypoint: ['']
  script:
    - flake8 --max-line-length 120 SHE_PPT

pytest:
  stage: test
  image:
    name: gitlab.euclid-sgs.uk:4567/pf-she/she_containers/el_utils:1.2.2
    entrypoint: [ '/bin/sh', '-c' ]
  variables:
    ELEMENTS_AUX_PATH: /usr/share/auxdir
    ELEMENTS_CONF_PATH: /usr/share/conf
    USER: $GITLAB_USER_LOGIN
  script:
    - mkdir build
    - cd build
    - cmake -DPYTHON_EXPLICIT_VERSION=3 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RELEASE ..
    - make install
    - pytest ../SHE_PPT/tests/python
